# Generated by Django 5.2.17 on 2026-09-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "key",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("window_start", models.DateTimeField()),
                ("failures", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
