# Generated by Django 5.2.17 on 2026-09-30 22:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlanVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("version", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=120)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(max_length=3)),
                (
                    "unit",
                    models.CharField(
                        choices=[("DAYS", "Días"), ("MONTHS", "Meses")], max_length=6
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_promotion", models.BooleanField(default=False)),
                ("available_from", models.DateField(null=True)),
                ("available_until", models.DateField(null=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="gym.plan",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("plan", "version"), name="plan_version_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount__gte", 0)),
                        name="plan_amount_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gte", 1)),
                        name="plan_quantity_positive",
                    ),
                ],
            },
        ),
    ]
