# Generated by Django 5.2.17 on 2026-10-02 14:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_rls'),
        ('gym', '0004_rls'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('local_date', models.DateField()),
                ('timezone', models.CharField(max_length=64)),
                ('decision', models.CharField(max_length=12)),
                ('service_status', models.CharField(max_length=24)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('request_id', models.UUIDField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.clientrecord')),
                ('membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gym.membership')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceVoid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=300)),
                ('request_id', models.UUIDField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='void_record', to='gym.attendance')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['workspace', 'local_date', 'client'], name='gym_attenda_workspa_c2259f_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('workspace', 'request_id'), name='attendance_request_unique'),
        ),
        migrations.AddConstraint(
            model_name='attendancevoid',
            constraint=models.UniqueConstraint(fields=('workspace', 'request_id'), name='attendance_void_request_unique'),
        ),
    ]
